version: "2"
run:
    timeout: "5m"
    allow-parallel-runners: true

linters:
    default: standard
    settings:
        errcheck:
            check-type-assertions: true
            check-blank: true
            disable-default-exclusions: false
            exclude-functions:
                # It doesn't return an error. Documented since go1.24.
                # errcheck have this as default but there isn't a new release.
                - crypto/rand.Read
            verbose: false

formatters:
    enable:
        - gofmt
        - gofumpt
        - goimports
