version: "2"
run:
    timeout: "5m"
    allow-parallel-runners: true

linters:
    # Default set of linters.
    # The value can be: `standard`, `all`, `none`, or `fast`.
    # Default: standard
    default: standard
