version: "3"

output: prefixed

dotenv: [".env"]

vars:
    TMP_DIR: "{{.ROOT_DIR}}/tmp"
    BIN_DIR: "{{.ROOT_DIR}}/bin"

    GUARDIAN_MAIN_PKG_PATH: "{{.ROOT_DIR}}/cmd/guardian"
    GUARDIAN_DEV_BIN: "{{.TMP_DIR}}/guardian"
    GUARDIAN_BIN: "{{.BIN_DIR}}/guardian"

    # Tools
    SQLC_PKG: "github.com/sqlc-dev/sqlc/cmd/sqlc"
    SQLC_VERSION: "latest"
    SQLC: "{{.BIN_DIR}}/sqlc"

    GOOSE_PKG: "github.com/pressly/goose/v3/cmd/goose"
    GOOSE_VERSION: "latest"
    GOOSE: "{{.BIN_DIR}}/goose"

    GOVULNCHECK_PKG: "golang.org/x/vuln/cmd/govulncheck"
    GOVULNCHECK_VERSION: "latest"
    GOVULNCHECK: "{{.BIN_DIR}}/govulncheck"

    AIR_PKG: "github.com/air-verse/air"
    AIR_VERSION: "latest"
    AIR: "{{.BIN_DIR}}/air"

    BUF_VERSION: "v1.60.0"
    BUF: "{{.BIN_DIR}}/buf"

    GOLANGCI_LINT_VERSION: "v2.6.2"
    GOLANGCI_LINT: "{{.BIN_DIR}}/golangci-lint"

    DOCKER_MONITORING_PROFILE: "--profile monitoring"
env:
    CGO_ENABLED: "0"
    GOBIN: "{{.BIN_DIR}}"

tasks:
    # ---------------------------------------------------------------------------- #
    #                                 Root Commands                                #
    # ---------------------------------------------------------------------------- #
    build:
        desc: Builds all.
        deps:
            - guardian:build

    generate:
        desc: Generate all.
        deps:
            - task: proto:generate
            - task: db:generate

    fmt:
        desc: Format all.
        deps:
            - task: go:fmt
            - task: proto:fmt
            - task: prettier:fmt

    dev:
        desc: Develop.
        deps:
            - task: guardian:dev

    spell-check:
        desc: Spell check.
        cmds:
            - pnpm run spell-check

    setup:
        desc: Setup development environment.
        cmds:
            - task: tools:install
            - task: docker:up
            - cp ./dev/guardian.dev.json ./guardian.json
            - task: guardian:build
            # - task: db migration up

    # ---------------------------------------------------------------------------- #
    #                               Guardian Commands                              #
    # ---------------------------------------------------------------------------- #
    guardian:build:
        desc: Build cmd/guardian.
        cmds:
            - 'go build -o {{q .GUARDIAN_BIN}} -trimpath -ldflags="{{.LINKER_FLAG}}" {{q .GUARDIAN_MAIN_PKG_PATH}}'
        vars:
            NOW: '{{now | date "2006-01-02T15:04:05Z07:00"}}'
            COMMIT_HASH_RAW:
                sh: "git log -n 1 --format=%h"
            COMMIT_HASH: "{{trim .COMMIT_HASH_RAW}}"
            BRANCH_RAW:
                sh: "git rev-parse --abbrev-ref HEAD"
            BRANCH: "{{trim .BRANCH_RAW}}"
            LINKER_FLAG: "-s -X main.commit={{q .COMMIT_HASH}} -X main.branch={{q .BRANCH}} -X main.buildTimeRFC3339={{q .NOW}}"

    guardian:run:
        desc: Run guardian.
        cmds:
            - "{{.GUARDIAN_BIN}} server"

    guardian:dev:build:
        desc: Build cmd/guardian for development.
        cmds:
            - "go build -o {{q .GUARDIAN_DEV_BIN}} {{q .GUARDIAN_MAIN_PKG_PATH}}"

    guardian:dev:
        desc: Build and run guardian and watch for files changes.
        cmds:
            - '{{.AIR}} -build.cmd "task guardian:dev:build" -build.bin {{q .GUARDIAN_DEV_BIN}} -build.args_bin server'

    # ---------------------------------------------------------------------------- #
    #                                  Go commands                                 #
    # ---------------------------------------------------------------------------- #
    go:fmt:
        desc: Format Go files.
        cmds:
            - "{{.GOLANGCI_LINT}} fmt"

    go:lint:
        desc: Lint Go files.
        cmds:
            - go vet ./...
            - "{{.GOLANGCI_LINT}} run"

    go:tidy:
        desc: Add missing and remove unused Go modules.
        cmds:
            - go mod tidy

    go:vuln:
        desc: Check for vulnerability in Go deps.
        cmds:
            - "{{.GOVULNCHECK}} ./..."

    # ---------------------------------------------------------------------------- #
    #                                Tools Commands                                #
    # ---------------------------------------------------------------------------- #
    tools:install:
        desc: Install tools.
        cmds:
            # These cmds uses recommended way of installation
            - go install {{.SQLC_PKG}}@{{.SQLC_VERSION}}
            - go install {{.GOOSE_PKG}}@{{.GOOSE_VERSION}}
            - go install {{.AIR_PKG}}@{{.AIR_VERSION}}
            - go install {{.GOVULNCHECK_PKG}}@{{.GOVULNCHECK_VERSION}}
            - curl -sSL "https://github.com/bufbuild/buf/releases/download/{{.BUF_VERSION}}/buf-$(uname -s)-$(uname -m)" -o {{q .BUF}} && chmod +x {{q .BUF}}
            - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b {{q .BIN_DIR}} {{.GOLANGCI_LINT_VERSION}}

    # ---------------------------------------------------------------------------- #
    #                                Docker commands                               #
    # ---------------------------------------------------------------------------- #
    docker:up:
        desc: Create and start required infra containers.
        cmds:
            - docker compose up -d

    docker:down:
        desc: Stop and remove required infra containers.
        cmds:
            - docker compose down

    docker:start:
        desc: Start required infra containers.
        cmds:
            - docker compose start

    docker:stop:
        desc: Stop required infra containers.
        cmds:
            - docker compose stop

    docker:restart:
        desc: Restart required infra containers.
        cmds:
            - docker compose restart

    docker:all:up:
        desc: Create and start all (with monitoring) infra containers.
        cmds:
            - docker compose {{.DOCKER_MONITORING_PROFILE}} up -d

    docker:all:down:
        desc: Stop and remove all (with monitoring) infra containers.
        cmds:
            - docker compose {{.DOCKER_MONITORING_PROFILE}} down

    docker:all:start:
        desc: Start all (with monitoring) infra containers.
        cmds:
            - docker compose {{.DOCKER_MONITORING_PROFILE}} start

    docker:all:stop:
        desc: Stop all (with monitoring) infra containers.
        cmds:
            - docker compose {{.DOCKER_MONITORING_PROFILE}} stop

    docker:all:restart:
        desc: Restart all (with monitoring) infra containers.
        cmds:
            - docker compose {{.DOCKER_MONITORING_PROFILE}} restart

    # ---------------------------------------------------------------------------- #
    #                               Database Commands                              #
    # ---------------------------------------------------------------------------- #
    db:migration:
        desc: Run db migrations.
        deps:
            - task: guardian:build
        cmds:
            - "{{.GUARDIAN_BIN}} migration {{.CLI_ARGS}}"

    db:generate:
        desc: Generate Go files for from SQL source.
        cmds:
            - "{{.SQLC}} generate"
        sources:
            - sqlc.yaml
            - internal/db/sql/**/*.sql

    db:lint:
        desc: Lint SQL files.
        cmds:
            - "{{.SQLC}} vet"

    # ---------------------------------------------------------------------------- #
    #                               Protobuf Commands                              #
    # ---------------------------------------------------------------------------- #
    proto:generate:
        desc: Generate code from protobuf files.
        cmds:
            - "{{.BUF}} generate"
        sources:
            - buf.yaml
            - buf.gen.yaml
            - buf.lock
            - proto/**/*

    proto:fmt:
        desc: Format protobuf files.
        cmds:
            - "{{.BUF}} format -w"

    proto:lint:
        desc: Lint protobuf files.
        cmds:
            - "{{.BUF}} lint"

    # ---------------------------------------------------------------------------- #
    #                               Prettier Commands                              #
    # ---------------------------------------------------------------------------- #
    prettier:fmt:
        desc: Format files with prettier.
        cmds:
            - pnpm run prettier:fmt
